/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-105513-g91326dc942-20220208"
#endif /* AVUTIL_FFVERSION_H */
